### ISSUE TITLE
Bug on update vscode

### ISSUE THREAD

**Issue by renatovitor01** [CarlosOrozco88/ui5-tools#25] opened 2023-01-13 12:08 UTC
Hi, I had a problem when my vscode was auto-updating.
The vscode showed a message: "Error... DeleteFile; code 32" (node_modules.asar in use).
I stopped extensions by extensions and the VSCode was updated after I stopped "ui5 tools".

On another notebook that had the same error, I stopped only "ui5-tools" and worked, vscode has been installed.

**To Reproduce**
1. Install the "ui5-tools" extension
2. Click to update vscode
3. If your vscode is not up to date, I think should give error.

**Expected behavior**
The message appears

**Comment by CarlosOrozco88** [comment] 2023-04-28 20:44
Hi, i forgot to reply your issue. I couldn't reproduce your problem, and none of my colleagues have had problems with the extension.
I will close this issue. Feel free to reopen If you still have the problem.

**Closed by CarlosOrozco88** 2023-04-28 20:44 UTC
